imageboard/urls.py
from django.conf.urls.static import static;
from django.conf import settings;
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT);

main/urls.py
from django.urls import path;

from . import views;

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_page, name="login"),
    path("logout", views.logout_page, name="logout"),
    path("register", views.register_page, name="register"),
    path("tag/", views.tag_list, name="tags"),
    path("tag/create/", views.tagcreate, name="tagcreate"),
    path("tag/<str:pk>/delete/", views.tag_delete, name="tagdelete"),

    path("user/<str:username>/", views.user_page, name="user"),

    path("artwork/<int:pk>/rmvote", views.artwork_rmvote, name="rmvote"),
    path("artwork/<int:pk>/upvote", views.artwork_upvote, name="upvote"),
    path("artwork/<int:pk>/downvote", views.artwork_downvote, name="downvote"),
    path("artwork/upload/", views.artwork_upload, name="upload"),
    path("artwork/<int:pk>/", views.imageview, name="imageview"),
    path("artwork/<int:pk>/delete/", views.artwork_delete, name="imagedelete"),
    path("artwork/<int:pk>/edit/", views.artwork_update, name="imageupdate"),
];

main/models.py
import os, time;
from django.contrib.auth.models import User
from django.db import models;

def rename_image(instance, filename) -> str:
    ext = os.path.splitext(filename)[1].lower();
    ut = int(time.time());
    return f"artworks/{ut}{ext}";

class Tag(models.Model):
    class Type(models.IntegerChoices):
        ARTIST = 1;
        CHARACTER = 2;
        SERIES = 3;

    name = models.CharField(max_length=50, primary_key=True);
    ttype = models.IntegerField(choices=Type);
    artwork_count = models.PositiveBigIntegerField(default=0);

class Artwork(models.Model):
    image = models.ImageField(upload_to=rename_image);
    uploadt = models.DateTimeField(auto_now_add=True);
    tags = models.ManyToManyField(Tag);
    score = models.BigIntegerField(default=0);

    uploader = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="artworks");

class ArtworkVote(models.Model):
    class Type(models.IntegerChoices):
        UPVOTE = 1;
        DOWNVOTE = -1;

    artwork = models.ForeignKey(
        Artwork,
        on_delete=models.CASCADE,
        related_name="votes");

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="artwork_votes");

    vtype = models.IntegerField(choices=Type);

    class Meta:
        unique_together = ("artwork", "user");

main/forms.py
# from django import 좃;
from django import forms;
from django.core.exceptions import ValidationError;

from main.models import Artwork, Tag;

class ImagePost(forms.ModelForm):
    tags = forms.CharField(required=False, widget=forms.Textarea(attrs={
        "rows": 3,
        "placeholder": "tags separated by space",
        "class": "max-w-md w-full p-2 border",
    }));

    def clean_tags(self):
        raw = self.cleaned_data["tags"]
        names = raw.split()

        tags = []
        missing = []

        for name in names:
            try:
                t = Tag.objects.get(name=name)
                tags.append(t)
            except Tag.DoesNotExist:
                missing.append(name)

        if missing:
            raise ValidationError(
                f"These tags don’t exist: {', '.join(missing)}"
            )

        return tags

    def save(self, commit=True):
        artwork = super().save(commit=False)
        tags = self.cleaned_data["tags"]
        if commit:
            artwork.save()
            artwork.tags.set(tags)
        return artwork

    class Meta:
        model = Artwork;
        fields = ["image", "tags"];

class ImageUpdate(forms.ModelForm):
    tags = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            "rows": 3,
            "placeholder": "tags separated by space",
            "class": "max-w-md w-full p-2 border",
        })
    );

    def clean_tags(self):
        raw = self.cleaned_data["tags"]
        names = raw.split()

        tags = []
        missing = []

        for name in names:
            try:
                t = Tag.objects.get(name=name)
                tags.append(t)
            except Tag.DoesNotExist:
                missing.append(name)

        if missing:
            raise ValidationError(
                f"Unknown tags: {', '.join(missing)}"
            )

        return tags

    def save(self, commit=True):
        artwork = super().save(commit=False)
        if commit:
            artwork.save()
            artwork.tags.set(self.cleaned_data["tags"])
        return artwork

    class Meta:
        model = Artwork;
        fields = ["tags"];

class TagCreation(forms.ModelForm):
    class Meta:
        model = Tag;
        fields = ["name", "ttype"];

main/views.py
import os;
from django.db.models.query import QuerySet
from django.db.models import Sum;
from django.db.transaction import commit
from django.http import HttpResponse;
from django.shortcuts import get_object_or_404, redirect, render;
from django.core.paginator import Paginator;

from django.contrib.auth import authenticate, get_user, login, logout;
from django.contrib.auth.decorators import login_required, user_passes_test;
from django.contrib.auth.models import User
from django.urls import reverse;

from main import forms, models

def mod_required(fn):
    return user_passes_test(lambda u: u.is_superuser, login_url="login")(fn)

def __handle_order_queries(
    what: str,
    posts: QuerySet[models.Artwork]) -> QuerySet:
    print("sorting by ", what);
    if what == "score":
        posts = posts.order_by("-score");
    elif what == "score_asc":
        posts = posts.order_by("score");
    elif what == "date_asc":
        posts = posts.order_by("uploadt");
    elif what == "date":
        posts = posts.order_by("-uploadt");
    else:
        posts = posts.order_by("-uploadt");
    return posts;

def index(request):
    tag_query = request.GET.get("q");
    posts: QuerySet[models.Artwork] = models.Artwork.objects.all();
    already_ordered: bool = False;

    if tag_query:
        tags = tag_query.split();
        for name in tags:
            if name[0] == '-':
                posts = posts.exclude(tags__name__iexact=name[1:]);
            elif name.startswith("order:"):
                posts = __handle_order_queries(name[6:], posts);
                already_ordered = True;
            elif name.startswith("uploader:"):
                username = name[9:];
                posts = posts.filter(uploader__username__iexact=username);
            else:
                posts = posts.filter(tags__name__iexact=name);

    if not already_ordered:
        posts = posts.order_by("-uploadt");
    paginator = Paginator(posts, 20);
    pagen = request.GET.get("page");
    page = paginator.get_page(pagen);

    poptags: set[models.Tag] = set();
    for artwork in page:
        for tag in artwork.tags.all():
            poptags.add(tag);

    return render(
        request,
        "list.html",
        {"page": page, "popular_tags": poptags}
    );

def imageview(request, pk):
    artwork = get_object_or_404(models.Artwork, pk=pk);
    return render(request, "imageview.html", {"artwork": artwork});

@login_required
def tagcreate(request):
    if request.method == "POST":
        form = forms.TagCreation(request.POST, request.FILES);
        if form.is_valid():
            form.save();
            return redirect("index");
    form = forms.TagCreation();
    return render(request, "tagcreate.html", {"form": form});

@mod_required
def tag_delete(request, pk):
    del request;
    tag = get_object_or_404(models.Tag, pk=pk);
    tag.delete();
    return redirect("index");

def tag_list(request):
    q = request.GET.get("q", "").strip()
    tags = models.Tag.objects.all()

    if q:
        tags = tags.filter(name__icontains=q)

    tags = tags.order_by("name")

    return render(request, "taglist.html", {
        "tags": tags,
        "query": q,
    })

def user_page(request, username):
    user = get_object_or_404(User, username=username)

    uploaded = models.Artwork.objects.filter(uploader=user).order_by("-uploadt")[:5]

    upvoted = models.Artwork.objects.filter(
        votes__user=user,
        votes__vtype=models.ArtworkVote.Type.UPVOTE,
    ).distinct()[:5]

    ctx = {
        "profile": user,
        "uploaded": uploaded,
        "upvoted": upvoted,
    }

    return render(request, "user.html", ctx)

@login_required
def artwork_upload(request):
    if request.method == "POST":
        form = forms.ImagePost(request.POST, request.FILES);
        if form.is_valid():
            artwork = form.save(commit=False);
            artwork.uploader = request.user;
            artwork.save();
            form.save(commit=True);
            return redirect("index");
    else:
        form = forms.ImagePost();
    return render(request, "upload.html", {"form": form});

@login_required
def artwork_update(request, pk):
    artwork: models.Artwork = get_object_or_404(models.Artwork, pk=pk);
    if request.method == "POST":
        form = forms.ImagePost(request.POST, instance=artwork);
        if form.is_valid():
            form.save(commit=True);
            return redirect("imageview", pk=artwork.pk);
    else:
        initial_tags = " ".join(t.name for t in artwork.tags.all());
        form = forms.ImageUpdate(instance=artwork, initial={"tags": initial_tags});
    return render(request, "imageupdate.html",
            {"form": form, "artwork": artwork});

@login_required
def artwork_rmvote(request, pk):
    artwork = get_object_or_404(models.Artwork, pk=pk);
    user = request.user;
    vote = models.ArtworkVote.objects \
        .filter(artwork=artwork, user=user) \
        .first();

    if vote:
        vote.delete();

        total = artwork.votes.aggregate(Sum('vtype'))['vtype__sum'] or 0;
        artwork.score = total;
        artwork.save(update_fields=['score']);

    q = request.GET.get('q', '')
    redirect_url = reverse('imageview', args=[pk])
    if q:
        redirect_url += f'?q={q}'

    return redirect(redirect_url);

@login_required
def artwork_upvote(request, pk):
    artwork: models.Artwork = get_object_or_404(models.Artwork, pk=pk);
    user = request.user;
    print(f"{user.username} {user.user_permissions}");

    vote, created = models.ArtworkVote.objects.get_or_create(
        artwork=artwork,
        user=user,
        defaults={'vtype': models.ArtworkVote.Type.UPVOTE}
    );

    if not created and vote.vtype == models.ArtworkVote.Type.UPVOTE:
        vote.delete();

    elif not created and vote.vtype != models.ArtworkVote.Type.UPVOTE:
        vote.vtype = models.ArtworkVote.Type.UPVOTE;
        vote.save();

    total = artwork.votes.aggregate(Sum('vtype'))['vtype__sum'] or 0;
    artwork.score = total;
    artwork.save(update_fields=['score']);

    q = request.GET.get('q', '')
    redirect_url = reverse('imageview', args=[pk])
    if q:
        redirect_url += f'?q={q}'

    return redirect(redirect_url);

@login_required
def artwork_downvote(request, pk):
    artwork: models.Artwork = get_object_or_404(models.Artwork, pk=pk);
    user = request.user;
    print(f"{user.username} {user.user_permissions}");

    vote, created = models.ArtworkVote.objects.get_or_create(
        artwork=artwork,
        user=user,
        defaults={'vtype': models.ArtworkVote.Type.DOWNVOTE}
    );

    if not created and vote.vtype == models.ArtworkVote.Type.DOWNVOTE:
        vote.delete();

    elif not created and vote.vtype != models.ArtworkVote.Type.DOWNVOTE:
        vote.vtype = models.ArtworkVote.Type.DOWNVOTE;
        vote.save();

    total = artwork.votes.aggregate(Sum('vtype'))['vtype__sum'] or 0;
    artwork.score = total;
    artwork.save(update_fields=['score']);

    q = request.GET.get('q', '')
    redirect_url = reverse('imageview', args=[pk])
    if q:
        redirect_url += f'?q={q}'

    return redirect(redirect_url);


@login_required
def artwork_delete(request, pk):
    del request;
    artwork: models.Artwork = get_object_or_404(models.Artwork, pk=pk);
    if artwork and os.path.isfile(artwork.image.path):
        os.remove(artwork.image.path);
    artwork.delete();
    return redirect("index");

def logout_page(request):
    logout(request);
    return redirect("index");

def register_page(request):
    if request.method == "POST":
        username = request.POST.get("username");
        password = request.POST.get("password");

        user = User.objects.filter(username=username);
        if user.exists():
            return redirect("register");

        user = User.objects.create_user(
            username=username
        );

        user.set_password(password);
        user.save();

        uauth = authenticate(
            username=username,
            password=password);
        if uauth is not None:
            login(request, uauth);
            return redirect("index");
        redirect("login");

    return render(request, "register.html");

def login_page(request):
    if request.method == "POST":
        username = request.POST.get("username");
        password = request.POST.get("password");

        if not User.objects.filter(username=username):
            return redirect("login");

        user = authenticate(
            username=username,
            password=password);
        if user is None:
            return redirect("login");
        else:
            login(request, user);
            return redirect("index");

    return render(request, "login.html");

main/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Imageboard{% endblock %}</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body>
    <a href="{% url 'index' %}" class="text-4xl p-4 font-bold">
        Imageboard
    </a>

    <div class="my-4 space-x-4 flex p-3 bg-rose-300">
        <a href="{% url 'upload' %}" class="font-bold">
            Upload
        </a>

        <a href="{% url 'tagcreate' %}" class="font-bold">
            Create tag
        </a>

        <a href="{% url 'tags' %}" class="font-bold">
            Tag list
        </a>

        {% if user.is_authenticated %}
            <a href="{% url 'user' user.username %}"
                <span class="font-bold text-blue-900"> {{ user.username }} </span>
            </a>
            <a href="{% url 'logout' %}" class="font-bold text-red-700">
                Logout
            </a>
        {% else %}
            <a href="{% url 'register' %}" class="font-bold">
                Register
            </a>
            <a href="{% url 'login' %}" class="font-bold">
                Login
            </a>
        {% endif %}
    </div>

    {% block content %}{% endblock %}
</body>
</html>

main/templates/imageupdate.html
{% extends "base.html" %}
{% block title %} Editing tags {% endblock %}

{% block content %}
<h1>Editing tags</h1>

<div class="flex h-screen">
<div class="w-1/3 p-6 break-words overflow-y-auto">
    <img id="preview" src="{{ artwork.image.url }}"
        class="max-h-full max-w-full object-contain">
</div>

<div class="flex-1 pt-6">
    <form method="post">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <p>
            {{ form.tags.label_tag }}
            {{ form.tags }}
            {{ form.tags.errors }}
        </p>

        <button type="submit" class="text-green-700 font-bold">
            Save changes
        </button>
    </form>

    <a href="{% url 'imageview' artwork.pk %}"
        class="text-red-500 font-bold">
        Cancel
    </a>
</div>
</div>

{% endblock %}

main/templates/imageview.html
{% extends "base.html" %}
{% block title %} Artwork view {% endblock %}

{% block content %}
<div class="flex h-screen">
    <div class="w-1/6 p-6 break-words overflow-y-auto">
        <form method="get" action="{% url 'index' %}">
        <input type="text" name="q" placeholder="Search tags"
            value="{{ request.GET.q }}"
            class="border p-1 w-full">
        <button type="submit" class="border bg-gray-200 p-1">
            Search
        </button>
    </form>
    <h3> Tags </h3>
        {% include "partials/tagbox.html" with tags=artwork.tags.all %}

    <a href="{% url 'upvote' artwork.pk %}?q={{ request.GET.q }}"
        class="text-blue-500 font-bold">
        Upvote
    </a>

    <a href="{% url 'downvote' artwork.pk %}?q={{ request.GET.q }}"
        class="text-blue-500 font-bold">
        Downvote
    </a>
    <br>

    <a href="{% url 'imagedelete' artwork.pk %}"
        class="text-red-600 font-bold"
        onclick="return confirm('Delete this artwork?');">
        Delete
    </a>
    <br>

    <a href="{% url 'imageupdate' artwork.pk %}"
        class="text-yellow-600 font-bold">
        Edit tags
    </a>
    <br>

    <p> Score: {{ artwork.score }} </p>

    <p> Uploader:
    <a href="{% url 'user' artwork.uploader.username %}"
            class="font-bold">
            {{ artwork.uploader.username }}
        </a>
    </p>
    <br>

    </div>

    <div class="flex-1 pt-6">
        <img src="{{ artwork.image.url }}"
            class="max-h-full max-w-full object-contain">
    </div>
</div>
{% endblock %}

main/templates/list.html
{% extends "base.html" %}
{% block title %} Imageboard {% endblock %}

{% block content %}
<div class="flex h-screen">
    <!-- Left panel (tags and search box) -->
    <div class="w-1/6 p-6 break-words overflow-y-auto">
        <form method="get">
            <input type="text" name="q" placeholder="Search tags"
                value="{{ request.GET.q }}"
                class="border p-1 w-full">
            <button type="submit" class="border bg-gray-200 p-1">
                Search
            </button>
        </form>

        <h3 class="font-semibold"> Popular tags </h3>
        {% include "partials/tagbox.html" with tags=popular_tags %}
    </div>

    <!-- Right panel (image listing) -->
    <div class="flex-1 p-6 overflow-y-auto">
    <div class="grid sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
        {% for post in page %}
            <div class="overflow-hidden">
                {% include "partials/ilst_image.html" with post=post %}
            </div>
        {% empty %}
            <p>No posts yet!</p>
        {% endfor %}
    </div>
    </div>
</div>

<!-- Pagination bullshits -->
<div class="flex justify-center space-x-4 p-2 mt-6">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}
            {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
           class="text-blue-500">-</a>
    {% endif %}

    {% for num in page.paginator.page_range %}
        {% if num == page.number %}
            <span class="text-black-900 font-bold">{{ num }}</span>
        {% elif num <= page.number|add:-3 or num >= page.number|add:3 %}
            {% if forloop.first or forloop.last %}
                <a class="text-blue-500" href="?page={{ num }}">{{ num }}</a>
            {% elif forloop.counter0 == 1 or forloop.counter0 == page.paginator.num_pages|add:-2 %}
                <span class="paginator-ellipsis">…</span>
            {% endif %}
        {% else %}
            <a class="text-blue-500" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}
            {% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
           class="text-blue-500">+</a>
    {% endif %}
</div>
{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}

{% block content %}
<h1>Login</h1>
<form method="post">
    {% csrf_token %}
    <p>
        <label for="username">Username:</label><br>
        <input type="text" name="username" id="username" required>
    </p>
    <p>
        <label for="password">Password:</label><br>
        <input type="password" name="password" id="password" required>
    </p>
    <button type="submit">Login</button>
</form>
<a href="{% url 'index' %}">Back to board</a>
{% endblock %}

main/templates/register.html
{% extends "base.html" %}
{% block title %} Register {% endblock %}

{% block content %}
<h1>Register</h1>
<form method="post">
    {% csrf_token %}
    <p>
        <label for="username">Username:</label><br>
        <input type="text" name="username" id="username" required>
    </p>
    <p>
        <label for="password">Password:</label><br>
        <input type="password" name="password" id="password" required>
    </p>
    <button type="submit">Create account</button>
</form>
<a href="{% url 'login' %}">Login?</a>
{% endblock %}

main/templates/tagcreate.html
{% extends "base.html" %}
{% block title %} Upload {% endblock %}

{% block content %}
<h1>Upload</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
<a href="{% url 'index' %}">Back to board</a>
{% endblock %}

main/templates/taglist.html
{% extends "base.html" %}
{% block title %}Manage Tags{% endblock %}

{% block content %}

{% if request.user.is_staff %}
    <h1 class="text-3xl font-bold mb-4">Tag manager</h1>
{% else %}
    <h1 class="text-3xl font-bold mb-4">Tag list</h1>
{% endif %}

<form method="get" class="mb-4 flex gap-2">
    <input type="text" name="q" value="{{ query }}"
           placeholder="search tags…"
           class="border p-2 w-64" />

    <button class="px-4 py-2 bg-blue-500 text-white">
        Search
    </button>
</form>

<table class="w-full border-collapse">
    <thead>
        <tr class="bg-gray-200 font-semibold text-left">
            <th class="p-2 border">Name</th>
            <th class="p-2 border">Type</th>
            <th class="p-2 border">Artwork Count</th>
            <th class="p-2 border">Actions</th>
        </tr>
    </thead>

    <tbody>
        {% for tag in tags %}
        <tr class="border hover:bg-gray-50">
            <td class="p-2 border">{{ tag.name }}</td>
            <td class="p-2 border">
                {{ tag.get_ttype_display }}
            </td>
            <td class="p-2 border">{{ tag.artwork_count }}</td>
            <td class="p-2 border">
                {% if request.user.is_staff %}
                    <a href="{% url 'tagdelete' tag.name %}"
                       class="px-2 py-1 bg-red-500 text-white">
                        Delete
                    </a>
                {% else %}
                    <button class="px-2 py-1 bg-gray-400 text-white opacity-50"
                            disabled>
                        Delete
                    </button>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4" class="p-4 text-center">
                No tags found.
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

main/templates/upload.html
{% extends "base.html" %}
{% block title %} Upload {% endblock %}

{% block content %}
<h1>Upload</h1>
<div class="flex h-screen">
<div class="w-1/3 p-6 break-words overflow-y-auto">
    <img id="preview" src="" class="max-h-full max-w-full object-contain">
</div>

<div class="flex-1 pt-6">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.non_field_errors }}

        <p>
            {{ form.image.label_tag }}
            {{ form.image }}
            {{ form.image.errors }}
        </p>

        <p>
            {{ form.tags.label_tag }}
            {{ form.tags }}
            {{ form.tags.errors }}
        </p>

        <button type="submit" class="text-green-700 font-bold">
            Upload
        </button>
    </form>


    <a href="{% url 'index' %}" class="text-red-500 font-bold"
        >Back to board
    </a>
</div>
</div>

<script>
    const fileInput = document.querySelector('input[type="file"]');
    const preview = document.getElementById('preview');

    fileInput.addEventListener('change', () => {
        const file = fileInput.files[0];
        if (file) {
            preview.src = URL.createObjectURL(file);
            preview.style.display = 'block';
        } else {
            preview.src = "";
            preview.style.display = 'none';
        }
    });
</script>
{% endblock %}

main/templates/user.html
{% extends "base.html" %}
{% block title %} User: {{ profile.username }} {% endblock %}

{% block content %}
<h1 class="text-3xl font-bold mb-4">
    {{ profile.username }}
</h1>

<div class="mb-6 space-y-1">
    <p>Date joined: {{ profile.date_joined }}</p>
    <p>Uploaded artworks: {{ uploaded.count }}</p>
</div>

<a href="{% url 'index' %}?q=uploader:{{ profile.username }}"
<h2 class="text-2xl font-semibold mb-2">Recent uploads</h2>
<div class="flex flex-wrap gap-3 mb-8">
    {% for post in uploaded %}
        {% include "partials/ilst_image.html" with post=post %}
    {% empty %}
        <p>No uploads yet.</p>
    {% endfor %}
</div>

<h2 class="text-2xl font-semibold mb-2">Recent upvoted</h2>
<div class="flex flex-wrap gap-3">
    {% for post in upvoted %}
        {% include "partials/ilst_image.html" with post=post %}
    {% empty %}
        <p>No upvotes yet.</p>
    {% endfor %}
</div>

{% endblock %}